#!/bin/bash

trim () { while read -r line; do echo "$line"; done; }

if [[ $(ls -A composer.json 2> /dev/null) ]]; then
    php_version_unformated=$(cat composer.json | grep '"php":' | trim)
    if [[ $php_version_unformated ]]; then
        php_version_dot=$(echo "$php_version_unformated" | cut -c9-11)
    else
        echo ""
        echo "Missing php version in composer.json"
        echo ""
        exit
    fi
else
    echo ""
    echo "File composer.json does not exist."
    echo ""
    exit
fi

app="$(basename "$0")"
command="$1"
options="$2"

#php_version_dot=$(php -r "\$v=explode('.', phpversion() ); echo implode('.', array_splice(\$v, 0, -1));")
php_version="${php_version_dot//./}"

xdebug_conf_path="$(brew --prefix)/etc/php/$php_version_dot/conf.d"
xdebug_conf_file="ext-xdebug.ini"
xdebug_conf=$xdebug_conf_path/$xdebug_conf_file
function keg_exists() { brew list php"${php_version}"-xdebug 2> /dev/null > /dev/null; }

if keg_exists; then
    if [ ! -f "$xdebug_conf" ] && [ ! -f "$xdebug_conf.disabled" ]; then
        echo ""
        echo "The ini file for Xdebug was not found at '$xdebug_conf_path'"
        echo "Did you install Xdebug via Homebrew?"
        echo ""

        exit 1
    else
        STATUS="enabled"
        IS_PHP_FPM=false
        SERVER_NAME="apache"

        if [ -f "$xdebug_conf" ] && [ -f "$xdebug_conf.disabled" ]; then
            echo ""
            echo "Detected both enabled and disabled Xdebug ini files. Deleting the disabled one."
            echo ""

            rm -rf "$xdebug_conf.disabled"
            STATUS="enabled"
        elif [ -f "$xdebug_conf.disabled" ]; then
            STATUS="disabled"
        fi

        if [ $# -ge 1 ] && [ "$command" == "on" ] || [ "$command" == "off" ]; then
            if [ "$command" == "on" ]; then
                mv "$xdebug_conf.disabled" "$xdebug_conf" 2> /dev/null
                STATUS="enabled"
            elif [ "$command" == "off" ]; then
                mv "$xdebug_conf" "$xdebug_conf.disabled" 2> /dev/null
                STATUS="disabled"
            fi

            if [ -f ~/Library/LaunchAgents/homebrew.mxcl.php"${php_version}".plist ]; then
                IS_PHP_FPM=true
                SERVER_NAME="php-fpm"
            fi

            if [ "$options" == '--no-server-restart' ]; then
                echo ""
                echo "Xdebug has been $STATUS. Will not restart $SERVER_NAME"
            else
                if [ "$IS_PHP_FPM" == true ]; then
                    echo ""
                    echo "Xdebug has been $STATUS, restarting $SERVER_NAME"

                    brew services restart php"${php_version}"
                else
                    echo ""
                    echo "Xdebug has been $STATUS, restarting $SERVER_NAME (it might ask for your password)"

                    sudo pkill -9 httpd
                    sudo apachectl -k restart > /dev/null 2>&1
                fi
            fi
        else
            echo ""
            echo "Usage: ${app} <on | off> [--no-server-restart]"
        fi

        echo ""
        echo "You are running PHP v$php_version_dot with Xdebug $STATUS"
        echo ""
    fi
fi